### ISSUE TITLE
Using (load-string) on a fact causes NullPointerException

### ISSUE THREAD

**Issue by eerohele** [marick/Midje#301]
I'm not really sure whether this is a bug in Leiningen or Midje or perhaps Clojure core, so apologies in advance if I'm creating this issue in the wrong place. I'd be happy to recreate this issue for the appropriate component if necessary.

Given:

``` clojure
; src/foobar/core.clj

(ns foobar.core
  (:use [midje.sweet :only (fact)]))

(load-string "(fact (+ 1 1) => 3)")
```

Then:

```
lein exec -p src/foobar/core.clj
```

Throws an NPE with this stack trace:

```
Exception in thread "main" java.lang.NullPointerException, compiling:(null:1:1)
    at clojure.lang.Compiler.load(Compiler.java:7142)
    at clojure.lang.Compiler.load(Compiler.java:7095)
    at clojure.core$load_reader.invoke(core.clj:3766)
    at clojure.core$load_string.invoke(core.clj:3776)
    at foobar.core$eval6464.invoke(core.clj:4)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.Compiler.loadFile(Compiler.java:7086)
    at clojure.lang.RT$3.invoke(RT.java:318)
    at user$eval5.invoke(form-init6181372544133469196.clj:1)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.eval(Compiler.java:6693)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    at clojure.lang.Compiler.loadFile(Compiler.java:7086)
    at clojure.main$load_script.invoke(main.clj:274)
    at clojure.main$init_opt.invoke(main.clj:279)
    at clojure.main$initialize.invoke(main.clj:307)
    at clojure.main$null_opt.invoke(main.clj:342)
    at clojure.main$main.doInvoke(main.clj:420)
    at clojure.lang.RestFn.invoke(RestFn.java:421)
    at clojure.lang.Var.invoke(Var.java:383)
    at clojure.lang.AFn.applyToHelper(AFn.java:156)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
Caused by: java.lang.NullPointerException
    at java.util.regex.Matcher.getTextLength(Matcher.java:1234)
    at java.util.regex.Matcher.reset(Matcher.java:308)
    at java.util.regex.Matcher.<init>(Matcher.java:228)
    at java.util.regex.Pattern.matcher(Pattern.java:1088)
    at clojure.core$re_matcher.invoke(core.clj:4460)
    at clojure.core$re_find.invoke(core.clj:4512)
    at midje.parsing.util.file_position$current_file_name.invoke(file_position.clj:57)
    at foobar.core$eval6466$fn__6467$fn__6468.invoke(Unknown Source)
    at midje.util.thread_safe_var_nesting$with_altered_roots_STAR_.invoke(thread_safe_var_nesting.clj:32)
    at foobar.core$eval6466$fn__6467.invoke(Unknown Source)
    at clojure.lang.AFn.applyToHelper(AFn.java:152)
    at clojure.lang.AFn.applyTo(AFn.java:144)
    at clojure.lang.AFunction$1.doInvoke(AFunction.java:29)
    at clojure.lang.RestFn.invoke(RestFn.java:397)
    at midje.checking.facts$check_one$fn__6167.invoke(facts.clj:31)
    at midje.checking.facts$check_one.invoke(facts.clj:30)
    at midje.checking.facts$creation_time_check.invoke(facts.clj:35)
    at foobar.core$eval6466.invoke(Unknown Source)
    at clojure.lang.Compiler.eval(Compiler.java:6703)
    at clojure.lang.Compiler.load(Compiler.java:7130)
    ... 23 more
Subprocess failed
```

Simply running `(load-string "(fact (+ 1 1) => 3)")` in a Leiningen REPL will also cause an NPE to be thrown (albeit without the stack trace). [SublimeREPL](https://github.com/wuub/SublimeREPL) uses `(load-string)` to evaluate Clojure code, so this issue prevents me from using it to check Midje facts directly from the editor.

Interestingly, doing `(eval (read-string "(fact (+ 1 1) => 3)"))` works fine.

Using OS X 10.10, Clojure 1.6.0, Leiningen 2.5.0 on Java 1.7.0_45 Java HotSpot(TM) 64-Bit Server VM.

**Comment by phillipm** [comment]
Fixed in https://github.com/marick/Midje/pull/409
