### ISSUE TITLE
Suchwow (1.8-alpha1) pulls in cljs... is it needed?

### ISSUE THREAD

**Issue by belucid** [marick/Midje#323]
This 1.8 [commit](https://github.com/marick/Midje/commit/7ba63f417f52f175a9a0285d95b555f2e66e112c) pulls in suchwow.

Looking at the deps-tree from 1.7 and 1.8, suchwow seems pretty heavyweight (pulls in cljs):

1.7:
```
[midje "1.7.0"]
    [colorize "0.1.1" :exclusions [[org.clojure/clojure]]]
    [dynapath "0.2.0"]
    [flare "0.2.8" :exclusions [[org.clojure/clojure]]]
    [ordered "1.2.0" :exclusions [[org.clojure/clojure]]]
    [org.clojure/core.unify "0.5.2" :exclusions [[org.clojure/clojure]]]
    [org.clojure/math.combinatorics "0.1.1"]
    [org.clojure/tools.namespace "0.2.7"]
    [org.tcrawley/dynapath "0.2.3"]
    [swiss-arrows "1.0.0" :exclusions [[org.clojure/clojure]]]
```

1.8
```
[midje "1.8-alpha1"]
    [backtick "0.3.2" :exclusions [[org.clojure/clojure]]]
    [colorize "0.1.1" :exclusions [[org.clojure/clojure]]]
    [flare "0.2.9" :exclusions [[org.clojure/clojure]]]
    [marick/clojure-commons "1.0.1" :exclusions [[org.clojure/clojure]]]
    [marick/suchwow "3.4.0" :exclusions [[org.clojure/clojure]]]
        [com.rpl/specter "0.6.2" :exclusions [[org.clojure/clojure]]]
            [org.clojure/clojurescript "0.0-3308"]
                [com.google.javascript/closure-compiler "v20150505"]
                    [args4j "2.0.26"]
                    [com.google.code.findbugs/jsr305 "1.3.9"]
                    [com.google.code.gson/gson "2.2.4"]
                    [com.google.guava/guava "18.0"]
                    [com.google.javascript/closure-compiler-externs "v20150505"]
                    [com.google.protobuf/protobuf-java "2.5.0"]
                [org.clojure/google-closure-library "0.0-20150505-021ed5b3"]
                    [org.clojure/google-closure-library-third-party "0.0-20150505-021ed5b3"]
                [org.mozilla/rhino "1.7R5"]
    [ordered "1.2.0" :exclusions [[org.clojure/clojure]]]
    [org.clojure/core.unify "0.5.2" :exclusions [[org.clojure/clojure]]]
    [org.clojure/math.combinatorics "0.1.1"]
    [org.clojure/tools.namespace "0.2.10"]
    [org.tcrawley/dynapath "0.2.3"]
    [swiss-arrows "1.0.0" :exclusions [[org.clojure/clojure]]]
    [traversy "0.3.1" :exclusions [[org.clojure/clojure]]]
```

One of the reasons I bring this up is that 1.8-alpha1 fails on my project (1.7 is fine):

```
Exception in thread "main" java.lang.IllegalArgumentException: No matching method: sha1Hex, compiling:(such/random.clj:17:3)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6798)
	at clojure.lang.Compiler.analyze(Compiler.java:6592)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6779)
	at clojure.lang.Compiler.analyze(Compiler.java:6592)
	at clojure.lang.Compiler.analyze(Compiler.java:6553)
	at clojure.lang.Compiler$BodyExpr$Parser.parse(Compiler.java:5929)
	at clojure.lang.Compiler$FnMethod.parse(Compiler.java:5359)
	at clojure.lang.Compiler$FnExpr.parse(Compiler.java:3959)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6789)
	at clojure.lang.Compiler.analyze(Compiler.java:6592)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6779)
	at clojure.lang.Compiler.analyze(Compiler.java:6592)
	at clojure.lang.Compiler.access$300(Compiler.java:38)
	at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:592)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6791)
	at clojure.lang.Compiler.analyze(Compiler.java:6592)
	at clojure.lang.Compiler.analyze(Compiler.java:6553)
	at clojure.lang.Compiler.eval(Compiler.java:6854)
	at clojure.lang.Compiler.load(Compiler.java:7295)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at such.immigration$import_all_vars$expand__413.invoke(immigration.clj:45)
	at such.immigration$import_all_vars$fn__415.invoke(immigration.clj:47)
	at clojure.core$map$fn__4553.invoke(core.clj:2624)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:681)
	at clojure.lang.Compiler.eval(Compiler.java:6838)
	at clojure.lang.Compiler.load(Compiler.java:7295)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:634)
	at clojure.core$use.doInvoke(core.clj:5843)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at midje.emission.levels$eval186$loading__5340__auto____187.invoke(levels.clj:1)
	at midje.emission.levels$eval186.invoke(levels.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6850)
	at clojure.lang.Compiler.eval(Compiler.java:6839)
	at clojure.lang.Compiler.load(Compiler.java:7295)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:512)
	at midje.config$eval105$loading__5340__auto____106.invoke(config.clj:1)
	at midje.config$eval105.invoke(config.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6850)
	at clojure.lang.Compiler.eval(Compiler.java:6839)
	at clojure.lang.Compiler.load(Compiler.java:7295)
	at clojure.lang.RT.loadResourceScript(RT.java:372)
	at clojure.lang.RT.loadResourceScript(RT.java:363)
	at clojure.lang.RT.load(RT.java:453)
	at clojure.lang.RT.load(RT.java:419)
	at clojure.core$load$fn__5448.invoke(core.clj:5866)
	at clojure.core$load.doInvoke(core.clj:5865)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$load_one.invoke(core.clj:5671)
	at clojure.core$load_lib$fn__5397.invoke(core.clj:5711)
	at clojure.core$load_lib.doInvoke(core.clj:5710)
	at clojure.lang.RestFn.applyTo(RestFn.java:142)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$load_libs.doInvoke(core.clj:5749)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invoke(core.clj:632)
	at clojure.core$require.doInvoke(core.clj:5832)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at user$eval101.invoke(form-init7489159739605733094.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6850)
	at clojure.lang.Compiler.eval(Compiler.java:6839)
	at clojure.lang.Compiler.eval(Compiler.java:6839)
	at clojure.lang.Compiler.load(Compiler.java:7295)
	at clojure.lang.Compiler.loadFile(Compiler.java:7233)
	at clojure.main$load_script.invoke(main.clj:275)
	at clojure.main$init_opt.invoke(main.clj:280)
	at clojure.main$initialize.invoke(main.clj:308)
	at clojure.main$null_opt.invoke(main.clj:343)
	at clojure.main$main.doInvoke(main.clj:421)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.IllegalArgumentException: No matching method: sha1Hex
	at clojure.lang.Compiler$StaticMethodExpr.<init>(Compiler.java:1658)
	at clojure.lang.Compiler$HostExpr$Parser.parse(Compiler.java:1014)
	at clojure.lang.Compiler.analyzeSeq(Compiler.java:6791)
	... 121 more
```

**Comment by marick** [comment]
Making Midje not pull in clojurescript is done.

I don't understand the second error. The jar is in the project file:

                 [commons-codec/commons-codec "1.10"]]

... and there is no more recent one according to `lein anceint`. When I look at the javadoc for DigestUtils, that method is there. 

I don't understand Maven very well at all. Are you doing anything odd in your project.clj file?

**Comment by marick** [comment]
Do you have the same problem when you use 1.8-alpha1 with the [sample Midje project](https://github.com/marick/sample-midje-project)?

**Comment by belucid** [comment]
@marick we do still get this in "1.8".

As far as I know, we're not doing anything unusual with the project file:

[https://github.com/open-company/open-company-auth/blob/mainline/project.clj](https://github.com/open-company/open-company-auth/blob/mainline/project.clj)

1.8 works fine on the [https://github.com/marick/sample-midje-project](sample Midje project) and on some [other projects](https://github.com/open-company/open-company-api/blob/mainline/project.clj) of ours.

It's quite strange.

**Comment by marick** [comment]
What happens when you do `lein deps :tree` on sample-midje-project (pull a new version, since I updated it to use released Midje 1.8.1)?

I get this:

```
 [cider/cider-nrepl "0.9.1"]
   [org.tcrawley/dynapath "0.2.3" :exclusions [[org.clojure/clojure]]]
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [midje "1.8.1" :scope "test"]
   [clj-time "0.11.0" :scope "test" :exclusions [[org.clojure/clojure]]]
     [joda-time "2.8.2" :scope "test"]
   [colorize "0.1.1" :scope "test" :exclusions [[org.clojure/clojure]]]
   [flare "0.2.9" :scope "test" :exclusions [[org.clojure/clojure]]]
     [org.clojars.brenton/google-diff-match-patch "0.1" :scope "test"]
   [marick/clojure-commons "1.1.1" :scope "test" :exclusions [[org.clojure/clojure]]]
   [marick/suchwow "4.4.0" :scope "test" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
     [com.rpl/specter "0.8.0" :scope "test" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
     [commons-codec "1.10" :scope "test"]
     [environ "1.0.1" :scope "test" :exclusions [[org.clojure/clojure]]]
     [potemkin "0.4.1" :scope "test" :exclusions [[org.clojure/clojure]]]
       [clj-tuple "0.2.2" :scope "test"]
       [riddley "0.1.10" :scope "test"]
   [ordered "1.2.0" :scope "test" :exclusions [[org.clojure/clojure]]]
   [org.clojure/core.unify "0.5.2" :scope "test" :exclusions [[org.clojure/clojure]]]
   [org.clojure/math.combinatorics "0.1.1" :scope "test"]
   [org.clojure/tools.macro "0.1.5" :scope "test"]
   [org.clojure/tools.namespace "0.2.10" :scope "test"]
   [slingshot "0.12.2" :scope "test"]
   [swiss-arrows "1.0.0" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.7.0"]
 [org.clojure/tools.nrepl "0.2.10" :scope "test" :exclusions [[org.clojure/clojure]]]
```
`lein deps` for Midje itself is:

```
 [cider/cider-nrepl "0.9.1"]
 [clj-time "0.11.0" :exclusions [[org.clojure/clojure]]]
   [joda-time "2.8.2"]
 [clojure-complete "0.2.3" :scope "test" :exclusions [[org.clojure/clojure]]]
 [colorize "0.1.1" :exclusions [[org.clojure/clojure]]]
 [flare "0.2.9" :exclusions [[org.clojure/clojure]]]
   [org.clojars.brenton/google-diff-match-patch "0.1"]
 [marick/clojure-commons "1.1.1" :exclusions [[org.clojure/clojure]]]
 [marick/suchwow "4.4.0" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
   [com.rpl/specter "0.8.0" :exclusions [[org.clojure/clojure] [org.clojure/clojurescript]]]
   [commons-codec "1.10"]
   [environ "1.0.1" :exclusions [[org.clojure/clojure]]]
   [potemkin "0.4.1" :exclusions [[org.clojure/clojure]]]
     [clj-tuple "0.2.2"]
     [riddley "0.1.10"]
 [ordered "1.2.0" :exclusions [[org.clojure/clojure]]]
 [org.clojure/clojure "1.6.0"]
 [org.clojure/core.unify "0.5.2" :exclusions [[org.clojure/clojure]]]
 [org.clojure/math.combinatorics "0.1.1"]
 [org.clojure/tools.macro "0.1.5"]
 [org.clojure/tools.namespace "0.2.10"]
 [org.clojure/tools.nrepl "0.2.10" :scope "test" :exclusions [[org.clojure/clojure]]]
 [org.tcrawley/dynapath "0.2.3"]
 [prismatic/plumbing "0.5.1" :scope "test"]
   [de.kotka/lazymap "3.1.0" :scope "test" :exclusions [[org.clojure/clojure]]]
   [prismatic/schema "1.0.1" :scope "test"]
 [slingshot "0.12.2"]
 [swiss-arrows "1.0.0" :exclusions [[org.clojure/clojure]]]
```

**Comment by ccfontes** [comment]
With `midje` 1.8.1, I also get the same issue.

`lein deps :tree`:
```
[compojure "1.4.0"] -> [ring/ring-codec "1.0.0"] -> [commons-codec "1.6"]
 overrides
[midje "1.8.1"] -> [marick/clojure-commons "1.1.1" :exclusions [org.clojure/clojure]] -> [marick/suchwow "4.1.0" :exclusions [org.clojure/clojure]] -> [commons-codec "1.10"]
 and
[midje "1.8.1"] -> [marick/suchwow "4.4.0" :exclusions [org.clojure/clojure org.clojure/clojurescript]] -> [commons-codec "1.10"]
...
   [ring/ring-codec "1.0.0"]
     [commons-codec "1.6"]
```

Doing `[compojure "1.4.0" :exclusions [commons-codec]]` solves it.

Maybe `commons-codec` should be upgraded in `compojure` instead?

**Comment by belucid** [comment]
Forcing it with an explicit dependency on commons-codec also worked in my projects:

```clojure
[commons-codec "1.10" :exclusions [[org.clojure/clojure]]]
```

**Comment by marick** [comment]
Yes, the problem is that compojure is out of date with its dependencies. I don't think there's any way for that to be solved inside Midje. I think how have to do the work in your own project file.
