### ISSUE TITLE
Unable to resolve symbol: _wrapping-target_ in this context

### ISSUE THREAD

**Issue by vbauer** [marick/Midje#340]
Hello, I've got the following problem on Travis CI after update to 1.8.2:

``` clojure
18.67s$ lein2 with-profile dev midje && lein2 uberjar
Error encountered performing task 'midje' with profile(s): 'dev'
java.lang.RuntimeException: Unable to resolve symbol: _wrapping-target_ in this context, compiling:(midje/repl.clj:32:3)
    at clojure.lang.Compiler.analyze(Compiler.java:6464)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$VectorExpr.parse(Compiler.java:3126)
    at clojure.lang.Compiler.analyze(Compiler.java:6447)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$InvokeExpr.parse(Compiler.java:3665)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6646)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$MapExpr.parse(Compiler.java:2981)
    at clojure.lang.Compiler.analyze(Compiler.java:6453)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
    at clojure.lang.Compiler$DefExpr$Parser.parse(Compiler.java:537)
    at clojure.lang.Compiler.analyzeSeq(Compiler.java:6644)
    at clojure.lang.Compiler.analyze(Compiler.java:6445)
    at clojure.lang.Compiler.analyze(Compiler.java:6406)
```

Additional information could be found here: https://travis-ci.org/vbauer/lein-plantuml/jobs/94066945

PS: Project still works fine on OS X El Capitan.

**Comment by marick** [comment]
Sorry for the delay. The error is bizarre: That's symbol is an unused argument to certain macroexpansions that shouldn't ever happen when loading `repl.clj`. It's also a little surprising that `repl.clj` is loaded at all in a `lein midje`. Do you load it explicitly? 

Can you make it happen in a reduced form in https://github.com/marick/sample-midje-project? (Or, if it's public, tell me what I can clone.)

**Comment by dlebrero** [comment]
Just had the same issue updating to the latest version of Midje. The issue was that one of the project dependencies (prismatic-schema in my case) had a dependency on an old version of potemkin (0.3.2). Manually depending on [potemkin "0.4.2"] in my project.clj fixed the issue.

**Comment by dkincaid** [comment]
Now I'm getting this error too after upping my project from clojure 1.6 to clojure 1.8.

**Comment by dkincaid** [comment]
I'm also getting this just by trying to upgrade the Cascalog-core version from 2.1.1 to 3.0.0. Not sure what's there that is messing midje up, but that's what I'm getting.

**Comment by phillipm** [comment]
Given the workaround presented in https://github.com/marick/Midje/issues/340#issuecomment-174741554 I'm going to close this out.
