### ISSUE TITLE
Midje does not support Specter 0.11.0

### ISSUE THREAD

**Issue by carnellj** [marick/Midje#361]
Trying to use Specter .11.0 with midje.  Getting the following error:

Caused by: java.lang.RuntimeException: No such var: specter/transform
	at clojure.lang.Util.runtimeException(Util.java:221)
	at clojure.lang.Compiler.resolveIn(Compiler.java:6993)
	at clojure.lang.Compiler.resolve(Compiler.java:6963)
	at clojure.lang.Compiler.analyzeSymbol(Compiler.java:6924)
	at clojure.lang.Compiler.analyze(Compiler.java:6506)
	... 140 more

Tracked it back to the fact that midje and two sub-projects all use Specter 0.9.2

**Comment by marick** [comment]
Fixed in 1.9.0-alpha2

**Comment by carnellj** [comment]
Awesome.  Thanks for responding back Brian.  Love Midje :-)
