### ISSUE TITLE
lein-midje is not compatible with lein 2.8.0 (latest release)

### ISSUE THREAD

**Issue by pmonks** [marick/Midje#406]
Running `lein midje` with Leiningen 2.8.0 (the latest release) results in `java.lang.RuntimeException: No reader function for tag object`.

Environment:
```
$ java -version
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)
$ lein --version
Leiningen 2.8.0 on Java 1.8.0_131 Java HotSpot(TM) 64-Bit Server VM
```

Full output of `lein midje` command, run against [this project](https://github.com/pmonks/spinner):
```
$ lein midje
Java HotSpot(TM) 64-Bit Server VM warning: Unable to open cgroup memory limit file /sys/fs/cgroup/memory/memory.limit_in_bytes (No such file or directory)
Exception in thread "main" java.lang.RuntimeException: No reader function for tag object, compiling:(/private/var/folders/gd/_mvxtqgd55vdxx76gq4bdx2w0000gn/T/form-init5582883654588722159.clj:1:8406)
	at clojure.lang.Compiler.load(Compiler.java:7386)
	at clojure.lang.Compiler.loadFile(Compiler.java:7317)
	at clojure.main$load_script.invokeStatic(main.clj:275)
	at clojure.main$init_opt.invokeStatic(main.clj:277)
	at clojure.main$init_opt.invoke(main.clj:277)
	at clojure.main$initialize.invokeStatic(main.clj:308)
	at clojure.main$null_opt.invokeStatic(main.clj:342)
	at clojure.main$null_opt.invoke(main.clj:339)
	at clojure.main$main.invokeStatic(main.clj:421)
	at clojure.main$main.doInvoke(main.clj:384)
	at clojure.lang.RestFn.invoke(RestFn.java:421)
	at clojure.lang.Var.invoke(Var.java:383)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.Var.applyTo(Var.java:700)
	at clojure.main.main(main.java:37)
Caused by: java.lang.RuntimeException: No reader function for tag object
	at clojure.lang.LispReader$CtorReader.readTagged(LispReader.java:1245)
	at clojure.lang.LispReader$CtorReader.invoke(LispReader.java:1228)
	at clojure.lang.LispReader$DispatchReader.invoke(LispReader.java:684)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:800)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:792)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$VectorReader.invoke(LispReader.java:1150)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:800)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$MapReader.invoke(LispReader.java:1158)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:200)
	at clojure.lang.LispReader.access$200(LispReader.java:40)
	at clojure.lang.LispReader$MetaReader.invoke(LispReader.java:792)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.readDelimitedList(LispReader.java:1200)
	at clojure.lang.LispReader$ListReader.invoke(LispReader.java:1049)
	at clojure.lang.LispReader.read(LispReader.java:263)
	at clojure.lang.LispReader.read(LispReader.java:196)
	at clojure.lang.Compiler.load(Compiler.java:7374)
	... 14 more
Subprocess failed
```

**Comment by phillipm** [comment]
Can you open this issue on the [`lein-midje` project](https://github.com/marick/lein-midje/issues)? I think it will make it easier to track.
That said, you might want to look into [this issue](https://github.com/technomancy/leiningen/issues/2321) on the `leiningen` project.

**Comment by pmonks** [comment]
Oh sorry - I completely spaced on `lein-midje` being a separate project.

And yeah I saw [that issue](https://github.com/technomancy/leiningen/issues/2321) earlier, and can confirm that I'm using JVM v1.8.0_131.
